apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
spec:
  # Use NodePort to easily access this from your local machine
  type: NodePort 
  selector:
    app: my-fastapi-app
  ports:
    - protocol: TCP
      port: 80       # The Service's internal port
      targetPort: 8000  # The port your container is listening on
      nodePort: 30007 # A fixed port to access from outside the cluster